# Force OS X.
language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9 HOMEBREW_RUBY=1.8.7
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - export TRAVIS_COMMIT=$(git rev-parse --verify -q HEAD)
  - cd /usr/local
  - sudo rm -rf /usr/local/.git/refs /usr/local/.git/packed-refs
  - sudo rsync -az "$TRAVIS_BUILD_DIR/" /usr/local/
  - export TRAVIS_BUILD_DIR="/usr/local"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - git reset --hard $TRAVIS_COMMIT
  - git clean -qxdff

install:
  - if [ "$HOMEBREW_RUBY" = "1.8.7" ]; then
      brew install homebrew/versions/ruby187;
      export PATH="/usr/local/opt/ruby187/bin:$PATH";
      export HOMEBREW_RUBY_PATH="/usr/local/opt/ruby187/bin/ruby";
    fi
  - export HOMEBREW_DEVELOPER="1"

script:
  - brew test-bot

notifications:
  email: false
